/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const AndexLazyRouteImport = createFileRoute('/andex')()
const dashboardLayoutLazyRouteImport = createFileRoute('/(dashboard)/_layout')()
const authRegisterLazyRouteImport = createFileRoute('/(auth)/register')()
const authLoginLazyRouteImport = createFileRoute('/(auth)/login')()
const dashboardLayoutProfilLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/profil',
)()
const dashboardLayoutDashboardLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/dashboard',
)()

const AndexLazyRoute = AndexLazyRouteImport.update({
  id: '/andex',
  path: '/andex',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/andex.lazy').then((d) => d.Route))
const dashboardLayoutLazyRoute = dashboardLayoutLazyRouteImport
  .update({
    id: '/(dashboard)/_layout',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(dashboard)/_layout.lazy').then((d) => d.Route))
const authRegisterLazyRoute = authRegisterLazyRouteImport
  .update({
    id: '/(auth)/register',
    path: '/register',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/register.lazy').then((d) => d.Route))
const authLoginLazyRoute = authLoginLazyRouteImport
  .update({
    id: '/(auth)/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/login.lazy').then((d) => d.Route))
const dashboardLayoutProfilLazyRoute = dashboardLayoutProfilLazyRouteImport
  .update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => dashboardLayoutLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(dashboard)/_layout/profil.lazy').then((d) => d.Route),
  )
const dashboardLayoutDashboardLazyRoute =
  dashboardLayoutDashboardLazyRouteImport
    .update({
      id: '/dashboard',
      path: '/dashboard',
      getParentRoute: () => dashboardLayoutLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/dashboard.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/andex': typeof AndexLazyRoute
  '/login': typeof authLoginLazyRoute
  '/register': typeof authRegisterLazyRoute
  '/dashboard': typeof dashboardLayoutDashboardLazyRoute
  '/profil': typeof dashboardLayoutProfilLazyRoute
}
export interface FileRoutesByTo {
  '/andex': typeof AndexLazyRoute
  '/login': typeof authLoginLazyRoute
  '/register': typeof authRegisterLazyRoute
  '/dashboard': typeof dashboardLayoutDashboardLazyRoute
  '/profil': typeof dashboardLayoutProfilLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/andex': typeof AndexLazyRoute
  '/(auth)/login': typeof authLoginLazyRoute
  '/(auth)/register': typeof authRegisterLazyRoute
  '/(dashboard)/_layout': typeof dashboardLayoutLazyRouteWithChildren
  '/(dashboard)/_layout/dashboard': typeof dashboardLayoutDashboardLazyRoute
  '/(dashboard)/_layout/profil': typeof dashboardLayoutProfilLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/andex' | '/login' | '/register' | '/dashboard' | '/profil'
  fileRoutesByTo: FileRoutesByTo
  to: '/andex' | '/login' | '/register' | '/dashboard' | '/profil'
  id:
    | '__root__'
    | '/andex'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(dashboard)/_layout'
    | '/(dashboard)/_layout/dashboard'
    | '/(dashboard)/_layout/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AndexLazyRoute: typeof AndexLazyRoute
  authLoginLazyRoute: typeof authLoginLazyRoute
  authRegisterLazyRoute: typeof authRegisterLazyRoute
  dashboardLayoutLazyRoute: typeof dashboardLayoutLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/andex': {
      id: '/andex'
      path: '/andex'
      fullPath: '/andex'
      preLoaderRoute: typeof AndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_layout': {
      id: '/(dashboard)/_layout'
      path: '/'
      fullPath: ''
      preLoaderRoute: typeof dashboardLayoutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_layout/profil': {
      id: '/(dashboard)/_layout/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof dashboardLayoutProfilLazyRouteImport
      parentRoute: typeof dashboardLayoutLazyRoute
    }
    '/(dashboard)/_layout/dashboard': {
      id: '/(dashboard)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardLayoutDashboardLazyRouteImport
      parentRoute: typeof dashboardLayoutLazyRoute
    }
  }
}

interface dashboardLayoutLazyRouteChildren {
  dashboardLayoutDashboardLazyRoute: typeof dashboardLayoutDashboardLazyRoute
  dashboardLayoutProfilLazyRoute: typeof dashboardLayoutProfilLazyRoute
}

const dashboardLayoutLazyRouteChildren: dashboardLayoutLazyRouteChildren = {
  dashboardLayoutDashboardLazyRoute: dashboardLayoutDashboardLazyRoute,
  dashboardLayoutProfilLazyRoute: dashboardLayoutProfilLazyRoute,
}

const dashboardLayoutLazyRouteWithChildren =
  dashboardLayoutLazyRoute._addFileChildren(dashboardLayoutLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AndexLazyRoute: AndexLazyRoute,
  authLoginLazyRoute: authLoginLazyRoute,
  authRegisterLazyRoute: authRegisterLazyRoute,
  dashboardLayoutLazyRoute: dashboardLayoutLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
