/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardLayoutRouteImport } from './routes/(dashboard)/_layout'
import { Route as dashboardLayoutNotificationsIndexRouteImport } from './routes/(dashboard)/_layout/notifications/index'
import { Route as dashboardLayoutMesFormationsIndexRouteImport } from './routes/(dashboard)/_layout/mes-formations/index'
import { Route as dashboardLayoutFormationsIndexRouteRouteImport } from './routes/(dashboard)/_layout/formations/index.route'
import { Route as dashboardLayoutProjetsAFinancerProjetIdRouteImport } from './routes/(dashboard)/_layout/projets-a-financer/$projetId'

const authRegisterLazyRouteImport = createFileRoute('/(auth)/register')()
const authLoginLazyRouteImport = createFileRoute('/(auth)/login')()
const dashboardLayoutProjetsSuivisLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/projets-suivis',
)()
const dashboardLayoutProfilLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/profil',
)()
const dashboardLayoutMentorsLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/mentors',
)()
const dashboardLayoutDemandesLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/demandes',
)()
const dashboardLayoutDashboardLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/dashboard',
)()
const dashboardLayoutReunionsIndexLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/reunions/',
)()
const dashboardLayoutProjetsIndexLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/projets/',
)()
const dashboardLayoutProjetsAFinancerIndexLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/projets-a-financer/',
)()
const dashboardLayoutMesFinancementsIndexLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/mes-financements/',
)()
const dashboardLayoutFinancementsIndexLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/financements/',
)()
const dashboardLayoutMesFormationsCreerLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/mes-formations/creer',
)()
const dashboardLayoutFinancementsFinancementIdLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/financements/$financementId',
)()
const dashboardLayoutReunionsReunionIdIndexLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/reunions/$reunionId/',
)()
const dashboardLayoutProjetsProjetIdIndexLazyRouteImport = createFileRoute(
  '/(dashboard)/_layout/projets/$projetId/',
)()
const dashboardLayoutMesFormationsFormationIdIndexLazyRouteImport =
  createFileRoute('/(dashboard)/_layout/mes-formations/$formationId/')()
const dashboardLayoutFormationsFormationIdIndexLazyRouteImport =
  createFileRoute('/(dashboard)/_layout/formations/$formationId/')()
const dashboardLayoutReunionsReunionIdRejoindreLazyRouteImport =
  createFileRoute('/(dashboard)/_layout/reunions/$reunionId/rejoindre')()
const dashboardLayoutMesFinancementsOffreIdCandidaturesLazyRouteImport =
  createFileRoute(
    '/(dashboard)/_layout/mes-financements/$offreId/candidatures',
  )()
const dashboardLayoutFormationsFormationIdLessonsIndexLazyRouteImport =
  createFileRoute('/(dashboard)/_layout/formations/$formationId/lessons/')()
const dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteImport =
  createFileRoute('/(dashboard)/_layout/projets/$projetId/stades/$numStade')()
const dashboardLayoutMesFormationsFormationIdLessonsCreerLazyRouteImport =
  createFileRoute(
    '/(dashboard)/_layout/mes-formations/$formationId/lessons/creer',
  )()
const dashboardLayoutMesFormationsFormationIdLessonsLessonIdIndexLazyRouteImport =
  createFileRoute(
    '/(dashboard)/_layout/mes-formations/$formationId/lessons/$lessonId/',
  )()
const dashboardLayoutFormationsFormationIdLessonsLessonIdIndexLazyRouteImport =
  createFileRoute(
    '/(dashboard)/_layout/formations/$formationId/lessons/$lessonId/',
  )()
const dashboardLayoutProjetsProjetIdStadesNumStadeDefinirMissionsLazyRouteImport =
  createFileRoute(
    '/(dashboard)/_layout/projets/$projetId/stades/$numStade/definir-missions',
  )()
const dashboardLayoutProjetsProjetIdStadesNumStadeMissionsMissionIdLazyRouteImport =
  createFileRoute(
    '/(dashboard)/_layout/projets/$projetId/stades/$numStade/missions/$missionId',
  )()

const authRegisterLazyRoute = authRegisterLazyRouteImport
  .update({
    id: '/(auth)/register',
    path: '/register',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/register.lazy').then((d) => d.Route))
const authLoginLazyRoute = authLoginLazyRouteImport
  .update({
    id: '/(auth)/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/login.lazy').then((d) => d.Route))
const dashboardLayoutRoute = dashboardLayoutRouteImport
  .update({
    id: '/(dashboard)/_layout',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(dashboard)/_layout.lazy').then((d) => d.Route))
const dashboardLayoutProjetsSuivisLazyRoute =
  dashboardLayoutProjetsSuivisLazyRouteImport
    .update({
      id: '/projets-suivis',
      path: '/projets-suivis',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/projets-suivis.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutProfilLazyRoute = dashboardLayoutProfilLazyRouteImport
  .update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)
  .lazy(() =>
    import('./routes/(dashboard)/_layout/profil.lazy').then((d) => d.Route),
  )
const dashboardLayoutMentorsLazyRoute = dashboardLayoutMentorsLazyRouteImport
  .update({
    id: '/mentors',
    path: '/mentors',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)
  .lazy(() =>
    import('./routes/(dashboard)/_layout/mentors.lazy').then((d) => d.Route),
  )
const dashboardLayoutDemandesLazyRoute = dashboardLayoutDemandesLazyRouteImport
  .update({
    id: '/demandes',
    path: '/demandes',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)
  .lazy(() =>
    import('./routes/(dashboard)/_layout/demandes.lazy').then((d) => d.Route),
  )
const dashboardLayoutDashboardLazyRoute =
  dashboardLayoutDashboardLazyRouteImport
    .update({
      id: '/dashboard',
      path: '/dashboard',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/dashboard.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutReunionsIndexLazyRoute =
  dashboardLayoutReunionsIndexLazyRouteImport
    .update({
      id: '/reunions/',
      path: '/reunions/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/reunions/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutProjetsIndexLazyRoute =
  dashboardLayoutProjetsIndexLazyRouteImport
    .update({
      id: '/projets/',
      path: '/projets/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/projets/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutProjetsAFinancerIndexLazyRoute =
  dashboardLayoutProjetsAFinancerIndexLazyRouteImport
    .update({
      id: '/projets-a-financer/',
      path: '/projets-a-financer/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/projets-a-financer/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutMesFinancementsIndexLazyRoute =
  dashboardLayoutMesFinancementsIndexLazyRouteImport
    .update({
      id: '/mes-financements/',
      path: '/mes-financements/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/mes-financements/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutFinancementsIndexLazyRoute =
  dashboardLayoutFinancementsIndexLazyRouteImport
    .update({
      id: '/financements/',
      path: '/financements/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/financements/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutNotificationsIndexRoute =
  dashboardLayoutNotificationsIndexRouteImport
    .update({
      id: '/notifications/',
      path: '/notifications/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/notifications/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutMesFormationsIndexRoute =
  dashboardLayoutMesFormationsIndexRouteImport
    .update({
      id: '/mes-formations/',
      path: '/mes-formations/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/mes-formations/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutFormationsIndexRouteRoute =
  dashboardLayoutFormationsIndexRouteRouteImport
    .update({
      id: '/formations/',
      path: '/formations',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/formations/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutMesFormationsCreerLazyRoute =
  dashboardLayoutMesFormationsCreerLazyRouteImport
    .update({
      id: '/mes-formations/creer',
      path: '/mes-formations/creer',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/mes-formations/creer.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutFinancementsFinancementIdLazyRoute =
  dashboardLayoutFinancementsFinancementIdLazyRouteImport
    .update({
      id: '/financements/$financementId',
      path: '/financements/$financementId',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/financements/$financementId.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutProjetsAFinancerProjetIdRoute =
  dashboardLayoutProjetsAFinancerProjetIdRouteImport
    .update({
      id: '/projets-a-financer/$projetId',
      path: '/projets-a-financer/$projetId',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/projets-a-financer/$projetId.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutReunionsReunionIdIndexLazyRoute =
  dashboardLayoutReunionsReunionIdIndexLazyRouteImport
    .update({
      id: '/reunions/$reunionId/',
      path: '/reunions/$reunionId/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/reunions/$reunionId/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutProjetsProjetIdIndexLazyRoute =
  dashboardLayoutProjetsProjetIdIndexLazyRouteImport
    .update({
      id: '/projets/$projetId/',
      path: '/projets/$projetId/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/projets/$projetId/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutMesFormationsFormationIdIndexLazyRoute =
  dashboardLayoutMesFormationsFormationIdIndexLazyRouteImport
    .update({
      id: '/mes-formations/$formationId/',
      path: '/mes-formations/$formationId/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/mes-formations/$formationId/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutFormationsFormationIdIndexLazyRoute =
  dashboardLayoutFormationsFormationIdIndexLazyRouteImport
    .update({
      id: '/formations/$formationId/',
      path: '/formations/$formationId/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/formations/$formationId/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutReunionsReunionIdRejoindreLazyRoute =
  dashboardLayoutReunionsReunionIdRejoindreLazyRouteImport
    .update({
      id: '/reunions/$reunionId/rejoindre',
      path: '/reunions/$reunionId/rejoindre',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/reunions/$reunionId/rejoindre.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutMesFinancementsOffreIdCandidaturesLazyRoute =
  dashboardLayoutMesFinancementsOffreIdCandidaturesLazyRouteImport
    .update({
      id: '/mes-financements/$offreId/candidatures',
      path: '/mes-financements/$offreId/candidatures',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/mes-financements/$offreId/candidatures.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutFormationsFormationIdLessonsIndexLazyRoute =
  dashboardLayoutFormationsFormationIdLessonsIndexLazyRouteImport
    .update({
      id: '/formations/$formationId/lessons/',
      path: '/formations/$formationId/lessons/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/formations/$formationId/lessons/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutProjetsProjetIdStadesNumStadeLazyRoute =
  dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteImport
    .update({
      id: '/projets/$projetId/stades/$numStade',
      path: '/projets/$projetId/stades/$numStade',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/projets/$projetId/stades/$numStade.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutMesFormationsFormationIdLessonsCreerLazyRoute =
  dashboardLayoutMesFormationsFormationIdLessonsCreerLazyRouteImport
    .update({
      id: '/mes-formations/$formationId/lessons/creer',
      path: '/mes-formations/$formationId/lessons/creer',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/mes-formations/$formationId/lessons/creer.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutMesFormationsFormationIdLessonsLessonIdIndexLazyRoute =
  dashboardLayoutMesFormationsFormationIdLessonsLessonIdIndexLazyRouteImport
    .update({
      id: '/mes-formations/$formationId/lessons/$lessonId/',
      path: '/mes-formations/$formationId/lessons/$lessonId/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/mes-formations/$formationId/lessons/$lessonId/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutFormationsFormationIdLessonsLessonIdIndexLazyRoute =
  dashboardLayoutFormationsFormationIdLessonsLessonIdIndexLazyRouteImport
    .update({
      id: '/formations/$formationId/lessons/$lessonId/',
      path: '/formations/$formationId/lessons/$lessonId/',
      getParentRoute: () => dashboardLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/formations/$formationId/lessons/$lessonId/index.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutProjetsProjetIdStadesNumStadeDefinirMissionsLazyRoute =
  dashboardLayoutProjetsProjetIdStadesNumStadeDefinirMissionsLazyRouteImport
    .update({
      id: '/definir-missions',
      path: '/definir-missions',
      getParentRoute: () =>
        dashboardLayoutProjetsProjetIdStadesNumStadeLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/projets/$projetId/stades/$numStade/definir-missions.lazy').then(
        (d) => d.Route,
      ),
    )
const dashboardLayoutProjetsProjetIdStadesNumStadeMissionsMissionIdLazyRoute =
  dashboardLayoutProjetsProjetIdStadesNumStadeMissionsMissionIdLazyRouteImport
    .update({
      id: '/missions/$missionId',
      path: '/missions/$missionId',
      getParentRoute: () =>
        dashboardLayoutProjetsProjetIdStadesNumStadeLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_layout/projets/$projetId/stades/$numStade/missions/$missionId.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/login': typeof authLoginLazyRoute
  '/register': typeof authRegisterLazyRoute
  '/dashboard': typeof dashboardLayoutDashboardLazyRoute
  '/demandes': typeof dashboardLayoutDemandesLazyRoute
  '/mentors': typeof dashboardLayoutMentorsLazyRoute
  '/profil': typeof dashboardLayoutProfilLazyRoute
  '/projets-suivis': typeof dashboardLayoutProjetsSuivisLazyRoute
  '/projets-a-financer/$projetId': typeof dashboardLayoutProjetsAFinancerProjetIdRoute
  '/financements/$financementId': typeof dashboardLayoutFinancementsFinancementIdLazyRoute
  '/mes-formations/creer': typeof dashboardLayoutMesFormationsCreerLazyRoute
  '/formations/': typeof dashboardLayoutFormationsIndexRouteRoute
  '/mes-formations/': typeof dashboardLayoutMesFormationsIndexRoute
  '/notifications/': typeof dashboardLayoutNotificationsIndexRoute
  '/financements/': typeof dashboardLayoutFinancementsIndexLazyRoute
  '/mes-financements/': typeof dashboardLayoutMesFinancementsIndexLazyRoute
  '/projets-a-financer/': typeof dashboardLayoutProjetsAFinancerIndexLazyRoute
  '/projets/': typeof dashboardLayoutProjetsIndexLazyRoute
  '/reunions/': typeof dashboardLayoutReunionsIndexLazyRoute
  '/mes-financements/$offreId/candidatures': typeof dashboardLayoutMesFinancementsOffreIdCandidaturesLazyRoute
  '/reunions/$reunionId/rejoindre': typeof dashboardLayoutReunionsReunionIdRejoindreLazyRoute
  '/formations/$formationId/': typeof dashboardLayoutFormationsFormationIdIndexLazyRoute
  '/mes-formations/$formationId/': typeof dashboardLayoutMesFormationsFormationIdIndexLazyRoute
  '/projets/$projetId/': typeof dashboardLayoutProjetsProjetIdIndexLazyRoute
  '/reunions/$reunionId/': typeof dashboardLayoutReunionsReunionIdIndexLazyRoute
  '/mes-formations/$formationId/lessons/creer': typeof dashboardLayoutMesFormationsFormationIdLessonsCreerLazyRoute
  '/projets/$projetId/stades/$numStade': typeof dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteWithChildren
  '/formations/$formationId/lessons/': typeof dashboardLayoutFormationsFormationIdLessonsIndexLazyRoute
  '/projets/$projetId/stades/$numStade/definir-missions': typeof dashboardLayoutProjetsProjetIdStadesNumStadeDefinirMissionsLazyRoute
  '/formations/$formationId/lessons/$lessonId/': typeof dashboardLayoutFormationsFormationIdLessonsLessonIdIndexLazyRoute
  '/mes-formations/$formationId/lessons/$lessonId/': typeof dashboardLayoutMesFormationsFormationIdLessonsLessonIdIndexLazyRoute
  '/projets/$projetId/stades/$numStade/missions/$missionId': typeof dashboardLayoutProjetsProjetIdStadesNumStadeMissionsMissionIdLazyRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginLazyRoute
  '/register': typeof authRegisterLazyRoute
  '/dashboard': typeof dashboardLayoutDashboardLazyRoute
  '/demandes': typeof dashboardLayoutDemandesLazyRoute
  '/mentors': typeof dashboardLayoutMentorsLazyRoute
  '/profil': typeof dashboardLayoutProfilLazyRoute
  '/projets-suivis': typeof dashboardLayoutProjetsSuivisLazyRoute
  '/projets-a-financer/$projetId': typeof dashboardLayoutProjetsAFinancerProjetIdRoute
  '/financements/$financementId': typeof dashboardLayoutFinancementsFinancementIdLazyRoute
  '/mes-formations/creer': typeof dashboardLayoutMesFormationsCreerLazyRoute
  '/formations': typeof dashboardLayoutFormationsIndexRouteRoute
  '/mes-formations': typeof dashboardLayoutMesFormationsIndexRoute
  '/notifications': typeof dashboardLayoutNotificationsIndexRoute
  '/financements': typeof dashboardLayoutFinancementsIndexLazyRoute
  '/mes-financements': typeof dashboardLayoutMesFinancementsIndexLazyRoute
  '/projets-a-financer': typeof dashboardLayoutProjetsAFinancerIndexLazyRoute
  '/projets': typeof dashboardLayoutProjetsIndexLazyRoute
  '/reunions': typeof dashboardLayoutReunionsIndexLazyRoute
  '/mes-financements/$offreId/candidatures': typeof dashboardLayoutMesFinancementsOffreIdCandidaturesLazyRoute
  '/reunions/$reunionId/rejoindre': typeof dashboardLayoutReunionsReunionIdRejoindreLazyRoute
  '/formations/$formationId': typeof dashboardLayoutFormationsFormationIdIndexLazyRoute
  '/mes-formations/$formationId': typeof dashboardLayoutMesFormationsFormationIdIndexLazyRoute
  '/projets/$projetId': typeof dashboardLayoutProjetsProjetIdIndexLazyRoute
  '/reunions/$reunionId': typeof dashboardLayoutReunionsReunionIdIndexLazyRoute
  '/mes-formations/$formationId/lessons/creer': typeof dashboardLayoutMesFormationsFormationIdLessonsCreerLazyRoute
  '/projets/$projetId/stades/$numStade': typeof dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteWithChildren
  '/formations/$formationId/lessons': typeof dashboardLayoutFormationsFormationIdLessonsIndexLazyRoute
  '/projets/$projetId/stades/$numStade/definir-missions': typeof dashboardLayoutProjetsProjetIdStadesNumStadeDefinirMissionsLazyRoute
  '/formations/$formationId/lessons/$lessonId': typeof dashboardLayoutFormationsFormationIdLessonsLessonIdIndexLazyRoute
  '/mes-formations/$formationId/lessons/$lessonId': typeof dashboardLayoutMesFormationsFormationIdLessonsLessonIdIndexLazyRoute
  '/projets/$projetId/stades/$numStade/missions/$missionId': typeof dashboardLayoutProjetsProjetIdStadesNumStadeMissionsMissionIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)/_layout': typeof dashboardLayoutRouteWithChildren
  '/(auth)/login': typeof authLoginLazyRoute
  '/(auth)/register': typeof authRegisterLazyRoute
  '/(dashboard)/_layout/dashboard': typeof dashboardLayoutDashboardLazyRoute
  '/(dashboard)/_layout/demandes': typeof dashboardLayoutDemandesLazyRoute
  '/(dashboard)/_layout/mentors': typeof dashboardLayoutMentorsLazyRoute
  '/(dashboard)/_layout/profil': typeof dashboardLayoutProfilLazyRoute
  '/(dashboard)/_layout/projets-suivis': typeof dashboardLayoutProjetsSuivisLazyRoute
  '/(dashboard)/_layout/projets-a-financer/$projetId': typeof dashboardLayoutProjetsAFinancerProjetIdRoute
  '/(dashboard)/_layout/financements/$financementId': typeof dashboardLayoutFinancementsFinancementIdLazyRoute
  '/(dashboard)/_layout/mes-formations/creer': typeof dashboardLayoutMesFormationsCreerLazyRoute
  '/(dashboard)/_layout/formations/': typeof dashboardLayoutFormationsIndexRouteRoute
  '/(dashboard)/_layout/mes-formations/': typeof dashboardLayoutMesFormationsIndexRoute
  '/(dashboard)/_layout/notifications/': typeof dashboardLayoutNotificationsIndexRoute
  '/(dashboard)/_layout/financements/': typeof dashboardLayoutFinancementsIndexLazyRoute
  '/(dashboard)/_layout/mes-financements/': typeof dashboardLayoutMesFinancementsIndexLazyRoute
  '/(dashboard)/_layout/projets-a-financer/': typeof dashboardLayoutProjetsAFinancerIndexLazyRoute
  '/(dashboard)/_layout/projets/': typeof dashboardLayoutProjetsIndexLazyRoute
  '/(dashboard)/_layout/reunions/': typeof dashboardLayoutReunionsIndexLazyRoute
  '/(dashboard)/_layout/mes-financements/$offreId/candidatures': typeof dashboardLayoutMesFinancementsOffreIdCandidaturesLazyRoute
  '/(dashboard)/_layout/reunions/$reunionId/rejoindre': typeof dashboardLayoutReunionsReunionIdRejoindreLazyRoute
  '/(dashboard)/_layout/formations/$formationId/': typeof dashboardLayoutFormationsFormationIdIndexLazyRoute
  '/(dashboard)/_layout/mes-formations/$formationId/': typeof dashboardLayoutMesFormationsFormationIdIndexLazyRoute
  '/(dashboard)/_layout/projets/$projetId/': typeof dashboardLayoutProjetsProjetIdIndexLazyRoute
  '/(dashboard)/_layout/reunions/$reunionId/': typeof dashboardLayoutReunionsReunionIdIndexLazyRoute
  '/(dashboard)/_layout/mes-formations/$formationId/lessons/creer': typeof dashboardLayoutMesFormationsFormationIdLessonsCreerLazyRoute
  '/(dashboard)/_layout/projets/$projetId/stades/$numStade': typeof dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteWithChildren
  '/(dashboard)/_layout/formations/$formationId/lessons/': typeof dashboardLayoutFormationsFormationIdLessonsIndexLazyRoute
  '/(dashboard)/_layout/projets/$projetId/stades/$numStade/definir-missions': typeof dashboardLayoutProjetsProjetIdStadesNumStadeDefinirMissionsLazyRoute
  '/(dashboard)/_layout/formations/$formationId/lessons/$lessonId/': typeof dashboardLayoutFormationsFormationIdLessonsLessonIdIndexLazyRoute
  '/(dashboard)/_layout/mes-formations/$formationId/lessons/$lessonId/': typeof dashboardLayoutMesFormationsFormationIdLessonsLessonIdIndexLazyRoute
  '/(dashboard)/_layout/projets/$projetId/stades/$numStade/missions/$missionId': typeof dashboardLayoutProjetsProjetIdStadesNumStadeMissionsMissionIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/dashboard'
    | '/demandes'
    | '/mentors'
    | '/profil'
    | '/projets-suivis'
    | '/projets-a-financer/$projetId'
    | '/financements/$financementId'
    | '/mes-formations/creer'
    | '/formations/'
    | '/mes-formations/'
    | '/notifications/'
    | '/financements/'
    | '/mes-financements/'
    | '/projets-a-financer/'
    | '/projets/'
    | '/reunions/'
    | '/mes-financements/$offreId/candidatures'
    | '/reunions/$reunionId/rejoindre'
    | '/formations/$formationId/'
    | '/mes-formations/$formationId/'
    | '/projets/$projetId/'
    | '/reunions/$reunionId/'
    | '/mes-formations/$formationId/lessons/creer'
    | '/projets/$projetId/stades/$numStade'
    | '/formations/$formationId/lessons/'
    | '/projets/$projetId/stades/$numStade/definir-missions'
    | '/formations/$formationId/lessons/$lessonId/'
    | '/mes-formations/$formationId/lessons/$lessonId/'
    | '/projets/$projetId/stades/$numStade/missions/$missionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/dashboard'
    | '/demandes'
    | '/mentors'
    | '/profil'
    | '/projets-suivis'
    | '/projets-a-financer/$projetId'
    | '/financements/$financementId'
    | '/mes-formations/creer'
    | '/formations'
    | '/mes-formations'
    | '/notifications'
    | '/financements'
    | '/mes-financements'
    | '/projets-a-financer'
    | '/projets'
    | '/reunions'
    | '/mes-financements/$offreId/candidatures'
    | '/reunions/$reunionId/rejoindre'
    | '/formations/$formationId'
    | '/mes-formations/$formationId'
    | '/projets/$projetId'
    | '/reunions/$reunionId'
    | '/mes-formations/$formationId/lessons/creer'
    | '/projets/$projetId/stades/$numStade'
    | '/formations/$formationId/lessons'
    | '/projets/$projetId/stades/$numStade/definir-missions'
    | '/formations/$formationId/lessons/$lessonId'
    | '/mes-formations/$formationId/lessons/$lessonId'
    | '/projets/$projetId/stades/$numStade/missions/$missionId'
  id:
    | '__root__'
    | '/(dashboard)/_layout'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(dashboard)/_layout/dashboard'
    | '/(dashboard)/_layout/demandes'
    | '/(dashboard)/_layout/mentors'
    | '/(dashboard)/_layout/profil'
    | '/(dashboard)/_layout/projets-suivis'
    | '/(dashboard)/_layout/projets-a-financer/$projetId'
    | '/(dashboard)/_layout/financements/$financementId'
    | '/(dashboard)/_layout/mes-formations/creer'
    | '/(dashboard)/_layout/formations/'
    | '/(dashboard)/_layout/mes-formations/'
    | '/(dashboard)/_layout/notifications/'
    | '/(dashboard)/_layout/financements/'
    | '/(dashboard)/_layout/mes-financements/'
    | '/(dashboard)/_layout/projets-a-financer/'
    | '/(dashboard)/_layout/projets/'
    | '/(dashboard)/_layout/reunions/'
    | '/(dashboard)/_layout/mes-financements/$offreId/candidatures'
    | '/(dashboard)/_layout/reunions/$reunionId/rejoindre'
    | '/(dashboard)/_layout/formations/$formationId/'
    | '/(dashboard)/_layout/mes-formations/$formationId/'
    | '/(dashboard)/_layout/projets/$projetId/'
    | '/(dashboard)/_layout/reunions/$reunionId/'
    | '/(dashboard)/_layout/mes-formations/$formationId/lessons/creer'
    | '/(dashboard)/_layout/projets/$projetId/stades/$numStade'
    | '/(dashboard)/_layout/formations/$formationId/lessons/'
    | '/(dashboard)/_layout/projets/$projetId/stades/$numStade/definir-missions'
    | '/(dashboard)/_layout/formations/$formationId/lessons/$lessonId/'
    | '/(dashboard)/_layout/mes-formations/$formationId/lessons/$lessonId/'
    | '/(dashboard)/_layout/projets/$projetId/stades/$numStade/missions/$missionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardLayoutRoute: typeof dashboardLayoutRouteWithChildren
  authLoginLazyRoute: typeof authLoginLazyRoute
  authRegisterLazyRoute: typeof authRegisterLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_layout': {
      id: '/(dashboard)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_layout/projets-suivis': {
      id: '/(dashboard)/_layout/projets-suivis'
      path: '/projets-suivis'
      fullPath: '/projets-suivis'
      preLoaderRoute: typeof dashboardLayoutProjetsSuivisLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/profil': {
      id: '/(dashboard)/_layout/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof dashboardLayoutProfilLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/mentors': {
      id: '/(dashboard)/_layout/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof dashboardLayoutMentorsLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/demandes': {
      id: '/(dashboard)/_layout/demandes'
      path: '/demandes'
      fullPath: '/demandes'
      preLoaderRoute: typeof dashboardLayoutDemandesLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/dashboard': {
      id: '/(dashboard)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardLayoutDashboardLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/reunions/': {
      id: '/(dashboard)/_layout/reunions/'
      path: '/reunions'
      fullPath: '/reunions/'
      preLoaderRoute: typeof dashboardLayoutReunionsIndexLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/projets/': {
      id: '/(dashboard)/_layout/projets/'
      path: '/projets'
      fullPath: '/projets/'
      preLoaderRoute: typeof dashboardLayoutProjetsIndexLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/projets-a-financer/': {
      id: '/(dashboard)/_layout/projets-a-financer/'
      path: '/projets-a-financer'
      fullPath: '/projets-a-financer/'
      preLoaderRoute: typeof dashboardLayoutProjetsAFinancerIndexLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/mes-financements/': {
      id: '/(dashboard)/_layout/mes-financements/'
      path: '/mes-financements'
      fullPath: '/mes-financements/'
      preLoaderRoute: typeof dashboardLayoutMesFinancementsIndexLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/financements/': {
      id: '/(dashboard)/_layout/financements/'
      path: '/financements'
      fullPath: '/financements/'
      preLoaderRoute: typeof dashboardLayoutFinancementsIndexLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/notifications/': {
      id: '/(dashboard)/_layout/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof dashboardLayoutNotificationsIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/mes-formations/': {
      id: '/(dashboard)/_layout/mes-formations/'
      path: '/mes-formations'
      fullPath: '/mes-formations/'
      preLoaderRoute: typeof dashboardLayoutMesFormationsIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/formations/': {
      id: '/(dashboard)/_layout/formations/'
      path: '/formations'
      fullPath: '/formations/'
      preLoaderRoute: typeof dashboardLayoutFormationsIndexRouteRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/mes-formations/creer': {
      id: '/(dashboard)/_layout/mes-formations/creer'
      path: '/mes-formations/creer'
      fullPath: '/mes-formations/creer'
      preLoaderRoute: typeof dashboardLayoutMesFormationsCreerLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/financements/$financementId': {
      id: '/(dashboard)/_layout/financements/$financementId'
      path: '/financements/$financementId'
      fullPath: '/financements/$financementId'
      preLoaderRoute: typeof dashboardLayoutFinancementsFinancementIdLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/projets-a-financer/$projetId': {
      id: '/(dashboard)/_layout/projets-a-financer/$projetId'
      path: '/projets-a-financer/$projetId'
      fullPath: '/projets-a-financer/$projetId'
      preLoaderRoute: typeof dashboardLayoutProjetsAFinancerProjetIdRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/reunions/$reunionId/': {
      id: '/(dashboard)/_layout/reunions/$reunionId/'
      path: '/reunions/$reunionId'
      fullPath: '/reunions/$reunionId/'
      preLoaderRoute: typeof dashboardLayoutReunionsReunionIdIndexLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/projets/$projetId/': {
      id: '/(dashboard)/_layout/projets/$projetId/'
      path: '/projets/$projetId'
      fullPath: '/projets/$projetId/'
      preLoaderRoute: typeof dashboardLayoutProjetsProjetIdIndexLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/mes-formations/$formationId/': {
      id: '/(dashboard)/_layout/mes-formations/$formationId/'
      path: '/mes-formations/$formationId'
      fullPath: '/mes-formations/$formationId/'
      preLoaderRoute: typeof dashboardLayoutMesFormationsFormationIdIndexLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/formations/$formationId/': {
      id: '/(dashboard)/_layout/formations/$formationId/'
      path: '/formations/$formationId'
      fullPath: '/formations/$formationId/'
      preLoaderRoute: typeof dashboardLayoutFormationsFormationIdIndexLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/reunions/$reunionId/rejoindre': {
      id: '/(dashboard)/_layout/reunions/$reunionId/rejoindre'
      path: '/reunions/$reunionId/rejoindre'
      fullPath: '/reunions/$reunionId/rejoindre'
      preLoaderRoute: typeof dashboardLayoutReunionsReunionIdRejoindreLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/mes-financements/$offreId/candidatures': {
      id: '/(dashboard)/_layout/mes-financements/$offreId/candidatures'
      path: '/mes-financements/$offreId/candidatures'
      fullPath: '/mes-financements/$offreId/candidatures'
      preLoaderRoute: typeof dashboardLayoutMesFinancementsOffreIdCandidaturesLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/formations/$formationId/lessons/': {
      id: '/(dashboard)/_layout/formations/$formationId/lessons/'
      path: '/formations/$formationId/lessons'
      fullPath: '/formations/$formationId/lessons/'
      preLoaderRoute: typeof dashboardLayoutFormationsFormationIdLessonsIndexLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/projets/$projetId/stades/$numStade': {
      id: '/(dashboard)/_layout/projets/$projetId/stades/$numStade'
      path: '/projets/$projetId/stades/$numStade'
      fullPath: '/projets/$projetId/stades/$numStade'
      preLoaderRoute: typeof dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/mes-formations/$formationId/lessons/creer': {
      id: '/(dashboard)/_layout/mes-formations/$formationId/lessons/creer'
      path: '/mes-formations/$formationId/lessons/creer'
      fullPath: '/mes-formations/$formationId/lessons/creer'
      preLoaderRoute: typeof dashboardLayoutMesFormationsFormationIdLessonsCreerLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/mes-formations/$formationId/lessons/$lessonId/': {
      id: '/(dashboard)/_layout/mes-formations/$formationId/lessons/$lessonId/'
      path: '/mes-formations/$formationId/lessons/$lessonId'
      fullPath: '/mes-formations/$formationId/lessons/$lessonId/'
      preLoaderRoute: typeof dashboardLayoutMesFormationsFormationIdLessonsLessonIdIndexLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/formations/$formationId/lessons/$lessonId/': {
      id: '/(dashboard)/_layout/formations/$formationId/lessons/$lessonId/'
      path: '/formations/$formationId/lessons/$lessonId'
      fullPath: '/formations/$formationId/lessons/$lessonId/'
      preLoaderRoute: typeof dashboardLayoutFormationsFormationIdLessonsLessonIdIndexLazyRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/_layout/projets/$projetId/stades/$numStade/definir-missions': {
      id: '/(dashboard)/_layout/projets/$projetId/stades/$numStade/definir-missions'
      path: '/definir-missions'
      fullPath: '/projets/$projetId/stades/$numStade/definir-missions'
      preLoaderRoute: typeof dashboardLayoutProjetsProjetIdStadesNumStadeDefinirMissionsLazyRouteImport
      parentRoute: typeof dashboardLayoutProjetsProjetIdStadesNumStadeLazyRoute
    }
    '/(dashboard)/_layout/projets/$projetId/stades/$numStade/missions/$missionId': {
      id: '/(dashboard)/_layout/projets/$projetId/stades/$numStade/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/projets/$projetId/stades/$numStade/missions/$missionId'
      preLoaderRoute: typeof dashboardLayoutProjetsProjetIdStadesNumStadeMissionsMissionIdLazyRouteImport
      parentRoute: typeof dashboardLayoutProjetsProjetIdStadesNumStadeLazyRoute
    }
  }
}

interface dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteChildren {
  dashboardLayoutProjetsProjetIdStadesNumStadeDefinirMissionsLazyRoute: typeof dashboardLayoutProjetsProjetIdStadesNumStadeDefinirMissionsLazyRoute
  dashboardLayoutProjetsProjetIdStadesNumStadeMissionsMissionIdLazyRoute: typeof dashboardLayoutProjetsProjetIdStadesNumStadeMissionsMissionIdLazyRoute
}

const dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteChildren: dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteChildren =
  {
    dashboardLayoutProjetsProjetIdStadesNumStadeDefinirMissionsLazyRoute:
      dashboardLayoutProjetsProjetIdStadesNumStadeDefinirMissionsLazyRoute,
    dashboardLayoutProjetsProjetIdStadesNumStadeMissionsMissionIdLazyRoute:
      dashboardLayoutProjetsProjetIdStadesNumStadeMissionsMissionIdLazyRoute,
  }

const dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteWithChildren =
  dashboardLayoutProjetsProjetIdStadesNumStadeLazyRoute._addFileChildren(
    dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteChildren,
  )

interface dashboardLayoutRouteChildren {
  dashboardLayoutDashboardLazyRoute: typeof dashboardLayoutDashboardLazyRoute
  dashboardLayoutDemandesLazyRoute: typeof dashboardLayoutDemandesLazyRoute
  dashboardLayoutMentorsLazyRoute: typeof dashboardLayoutMentorsLazyRoute
  dashboardLayoutProfilLazyRoute: typeof dashboardLayoutProfilLazyRoute
  dashboardLayoutProjetsSuivisLazyRoute: typeof dashboardLayoutProjetsSuivisLazyRoute
  dashboardLayoutProjetsAFinancerProjetIdRoute: typeof dashboardLayoutProjetsAFinancerProjetIdRoute
  dashboardLayoutFinancementsFinancementIdLazyRoute: typeof dashboardLayoutFinancementsFinancementIdLazyRoute
  dashboardLayoutMesFormationsCreerLazyRoute: typeof dashboardLayoutMesFormationsCreerLazyRoute
  dashboardLayoutFormationsIndexRouteRoute: typeof dashboardLayoutFormationsIndexRouteRoute
  dashboardLayoutMesFormationsIndexRoute: typeof dashboardLayoutMesFormationsIndexRoute
  dashboardLayoutNotificationsIndexRoute: typeof dashboardLayoutNotificationsIndexRoute
  dashboardLayoutFinancementsIndexLazyRoute: typeof dashboardLayoutFinancementsIndexLazyRoute
  dashboardLayoutMesFinancementsIndexLazyRoute: typeof dashboardLayoutMesFinancementsIndexLazyRoute
  dashboardLayoutProjetsAFinancerIndexLazyRoute: typeof dashboardLayoutProjetsAFinancerIndexLazyRoute
  dashboardLayoutProjetsIndexLazyRoute: typeof dashboardLayoutProjetsIndexLazyRoute
  dashboardLayoutReunionsIndexLazyRoute: typeof dashboardLayoutReunionsIndexLazyRoute
  dashboardLayoutMesFinancementsOffreIdCandidaturesLazyRoute: typeof dashboardLayoutMesFinancementsOffreIdCandidaturesLazyRoute
  dashboardLayoutReunionsReunionIdRejoindreLazyRoute: typeof dashboardLayoutReunionsReunionIdRejoindreLazyRoute
  dashboardLayoutFormationsFormationIdIndexLazyRoute: typeof dashboardLayoutFormationsFormationIdIndexLazyRoute
  dashboardLayoutMesFormationsFormationIdIndexLazyRoute: typeof dashboardLayoutMesFormationsFormationIdIndexLazyRoute
  dashboardLayoutProjetsProjetIdIndexLazyRoute: typeof dashboardLayoutProjetsProjetIdIndexLazyRoute
  dashboardLayoutReunionsReunionIdIndexLazyRoute: typeof dashboardLayoutReunionsReunionIdIndexLazyRoute
  dashboardLayoutMesFormationsFormationIdLessonsCreerLazyRoute: typeof dashboardLayoutMesFormationsFormationIdLessonsCreerLazyRoute
  dashboardLayoutProjetsProjetIdStadesNumStadeLazyRoute: typeof dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteWithChildren
  dashboardLayoutFormationsFormationIdLessonsIndexLazyRoute: typeof dashboardLayoutFormationsFormationIdLessonsIndexLazyRoute
  dashboardLayoutFormationsFormationIdLessonsLessonIdIndexLazyRoute: typeof dashboardLayoutFormationsFormationIdLessonsLessonIdIndexLazyRoute
  dashboardLayoutMesFormationsFormationIdLessonsLessonIdIndexLazyRoute: typeof dashboardLayoutMesFormationsFormationIdLessonsLessonIdIndexLazyRoute
}

const dashboardLayoutRouteChildren: dashboardLayoutRouteChildren = {
  dashboardLayoutDashboardLazyRoute: dashboardLayoutDashboardLazyRoute,
  dashboardLayoutDemandesLazyRoute: dashboardLayoutDemandesLazyRoute,
  dashboardLayoutMentorsLazyRoute: dashboardLayoutMentorsLazyRoute,
  dashboardLayoutProfilLazyRoute: dashboardLayoutProfilLazyRoute,
  dashboardLayoutProjetsSuivisLazyRoute: dashboardLayoutProjetsSuivisLazyRoute,
  dashboardLayoutProjetsAFinancerProjetIdRoute:
    dashboardLayoutProjetsAFinancerProjetIdRoute,
  dashboardLayoutFinancementsFinancementIdLazyRoute:
    dashboardLayoutFinancementsFinancementIdLazyRoute,
  dashboardLayoutMesFormationsCreerLazyRoute:
    dashboardLayoutMesFormationsCreerLazyRoute,
  dashboardLayoutFormationsIndexRouteRoute:
    dashboardLayoutFormationsIndexRouteRoute,
  dashboardLayoutMesFormationsIndexRoute:
    dashboardLayoutMesFormationsIndexRoute,
  dashboardLayoutNotificationsIndexRoute:
    dashboardLayoutNotificationsIndexRoute,
  dashboardLayoutFinancementsIndexLazyRoute:
    dashboardLayoutFinancementsIndexLazyRoute,
  dashboardLayoutMesFinancementsIndexLazyRoute:
    dashboardLayoutMesFinancementsIndexLazyRoute,
  dashboardLayoutProjetsAFinancerIndexLazyRoute:
    dashboardLayoutProjetsAFinancerIndexLazyRoute,
  dashboardLayoutProjetsIndexLazyRoute: dashboardLayoutProjetsIndexLazyRoute,
  dashboardLayoutReunionsIndexLazyRoute: dashboardLayoutReunionsIndexLazyRoute,
  dashboardLayoutMesFinancementsOffreIdCandidaturesLazyRoute:
    dashboardLayoutMesFinancementsOffreIdCandidaturesLazyRoute,
  dashboardLayoutReunionsReunionIdRejoindreLazyRoute:
    dashboardLayoutReunionsReunionIdRejoindreLazyRoute,
  dashboardLayoutFormationsFormationIdIndexLazyRoute:
    dashboardLayoutFormationsFormationIdIndexLazyRoute,
  dashboardLayoutMesFormationsFormationIdIndexLazyRoute:
    dashboardLayoutMesFormationsFormationIdIndexLazyRoute,
  dashboardLayoutProjetsProjetIdIndexLazyRoute:
    dashboardLayoutProjetsProjetIdIndexLazyRoute,
  dashboardLayoutReunionsReunionIdIndexLazyRoute:
    dashboardLayoutReunionsReunionIdIndexLazyRoute,
  dashboardLayoutMesFormationsFormationIdLessonsCreerLazyRoute:
    dashboardLayoutMesFormationsFormationIdLessonsCreerLazyRoute,
  dashboardLayoutProjetsProjetIdStadesNumStadeLazyRoute:
    dashboardLayoutProjetsProjetIdStadesNumStadeLazyRouteWithChildren,
  dashboardLayoutFormationsFormationIdLessonsIndexLazyRoute:
    dashboardLayoutFormationsFormationIdLessonsIndexLazyRoute,
  dashboardLayoutFormationsFormationIdLessonsLessonIdIndexLazyRoute:
    dashboardLayoutFormationsFormationIdLessonsLessonIdIndexLazyRoute,
  dashboardLayoutMesFormationsFormationIdLessonsLessonIdIndexLazyRoute:
    dashboardLayoutMesFormationsFormationIdLessonsLessonIdIndexLazyRoute,
}

const dashboardLayoutRouteWithChildren = dashboardLayoutRoute._addFileChildren(
  dashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardLayoutRoute: dashboardLayoutRouteWithChildren,
  authLoginLazyRoute: authLoginLazyRoute,
  authRegisterLazyRoute: authRegisterLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
